Error Handle Redux
TankGameOrg/engine pull request #60
Opened 2024-05-11 22:47 UTC by TrevorBrunette

2024-06-02 01:46 UTC, BryanFriestad requested changes

2024-06-02 01:46 UTC, BryanFriestad commented on src/main/java/pro/trevor/tankgame/rule/definition/player/Condition.java
> +public class Condition<T extends IPlayerElement> {
`T extends IPlayerElement` should just be T. For this and for Predicate

2024-06-02 01:46 UTC, BryanFriestad commented on src/main/java/pro/trevor/tankgame/rule/impl/version4/Ruleset.java
> +        playerRules.put(Tank.class, PlayerRules.GetShareGoldWithTaxRule(1));
Revert this

2024-06-24 04:46 UTC, BryanFriestad requested changes

2024-06-24 04:46 UTC, BryanFriestad commented on src/main/java/pro/trevor/tankgame/state/attribute/Attribute.java
I don't see a reason for this change. I think it is working fine to use Optional externally.

2024-07-07 15:51 UTC, ryan3r approved these changes

2024-07-09 03:03 UTC, merged