Rule Fixes
TankGameOrg/engine pull request #73
Opened 2024-07-04 17:40 UTC by TrevorBrunette

Simple rule fixes:
* Council needs 3 or more players to grant life
* Bounty can only happen if the council has enough coffer
* Code blocks replaced with lambdas where applicable

2024-07-04 19:01 UTC, ryan3r requested changes

2024-07-04 19:01 UTC, ryan3r commented on src/main/java/pro/trevor/tankgame/rule/impl/version3/Ruleset.java
> +        playerRules.put(Council.class, PlayerRules.GetRuleCofferCostBounty(1, 5));
Down with the code duplication!  We love to see it.

2024-07-04 19:01 UTC, ryan3r commented on src/main/java/pro/trevor/tankgame/rule/impl/shared/rule/PlayerRules.java
> +    public static PlayerActionRule<Council> GetRuleCofferCostBounty(int lowerBound, int upperBound) {
Please add a unit test for bounty.  You can probably copy the grant life tests.

2024-07-04 19:02 UTC, ryan3r commented on src/main/java/pro/trevor/tankgame/rule/impl/shared/rule/PlayerRules.java
> +                (s, c, n) -> {
Note: I'm not requiring this just suggesting

2024-07-04 19:06 UTC, TrevorBrunette commented on src/main/java/pro/trevor/tankgame/rule/impl/shared/rule/PlayerRules.java
> +                    return Attribute.DEAD.in(t) && Attribute.DURABILITY.in(t) && Attribute.COFFER.unsafeFrom(c) >= cost
Tanks do not have to be dead for them to be able to be granted life.

2024-07-04 20:47 UTC, ryan3r commented on src/main/java/pro/trevor/tankgame/rule/impl/shared/rule/PlayerRules.java
> +                    return Attribute.DEAD.in(t) && Attribute.DURABILITY.in(t) && Attribute.COFFER.unsafeFrom(c) >= cost
Oh, then why is there a check for dead?

2024-07-05 15:46 UTC, TrevorBrunette commented on src/main/java/pro/trevor/tankgame/rule/impl/shared/rule/PlayerRules.java
> +                    return Attribute.DEAD.in(t) && Attribute.DURABILITY.in(t) && Attribute.COFFER.unsafeFrom(c) >= cost
Grant life is checking to ensure that the generic tank is capable of being dead (Attribute.DEAD.in is not Attribute.DEAD.from)

2024-07-05 16:55 UTC, ryan3r approved these changes

2024-07-05 16:56 UTC, merged