Basic e2e
TankGameOrg/engine pull request #79
Opened 2024-07-13 03:58 UTC by TrevorBrunette

Basic end-to-end testing of board state

2024-07-14 22:38 UTC, ryan3r requested changes
Test cases not present that would be good to add at somepoint

* Gold mine locations (did they grow correctly)
* Empty tiles around gold mine (didn't grow too far)
* Wall health/locations

2024-07-14 22:38 UTC, ryan3r commented on src/test/java/pro/trevor/tankgame/e2e/EndToEndTestUtils.java
> +        noTanks.forEach((p) -> assertFalse(tester.getBoard().gatherUnits(GenericTank.class)
I don't think there is a case where this catches anything.  Between actualLivingTanks and actualDeadTanks one of them should complain that there's an extra tank on the board.

2024-07-14 22:38 UTC, ryan3r commented on src/test/java/pro/trevor/tankgame/e2e/EndToEndTestUtils.java
> +    public static <T> void assertPlayerAttributeEquals(EndToEndTester tester, String player, Attribute<T> attribute, T value) {
```suggestion
    public static <T> void assertPlayerElementAttributeEquals(EndToEndTester tester, String player, Attribute<T> attribute, T value) {
```
This checks the player element's attributes not the actual player attributes

2024-07-14 22:38 UTC, ryan3r commented on src/test/java/pro/trevor/tankgame/e2e/TestEndToEndV3.java
> +        tester.getCouncil().getCouncillors().forEach((p) -> assertFalse(tester.getCouncil().isPlayerSenator(p)));
These seems like a generic checks that would happen on most versions.  Helper function?

2024-07-15 03:10 UTC, TrevorBrunette commented
> Test cases not present that would be good to add at somepoint
> 
> * Gold mine locations (did they grow correctly)
> * Empty tiles around gold mine (didn't grow too far)
> * Wall health/locations

Added.

2024-07-16 00:19 UTC, ryan3r approved these changes

2024-07-16 02:58 UTC, merged