Move Actions with Speed
TankGameOrg/engine pull request #89
Opened 2024-08-17 21:22 UTC by TrevorBrunette

2024-08-18 04:24 UTC, ryan3r commented
Unit test path finding
 * Going around a wall
 * Faster path discovered later
 * Diagonal move blocked
 * Greater than 1 speed

2024-08-18 04:25 UTC, ryan3r requested changes

2024-08-18 04:25 UTC, ryan3r commented on src/main/java/pro/trevor/tankgame/util/Util.java
> +    public static HashMap<Position, Pair<Integer, Position>> allPossiblePaths(Board board, Position p, int speed) {
Please use full variable names (not p, same comment on other methods).  I appreciate the documentation.  

The use case for getting the whole path is for move animations.  It's probably better to keep this methods private for now (it exposes a lot of details) and add a method that constructs the single path that the player took when we need it.

2024-08-22 17:36 UTC, TrevorBrunette commented
> Unit test path finding
> 
> * Going around a wall
> * Faster path discovered later
> * Diagonal move blocked
> * Greater than 1 speed

Done

2024-08-22 18:46 UTC, ryan3r requested changes

2024-08-23 03:36 UTC, ryan3r approved these changes

2024-08-23 03:36 UTC, merged